/**
 * NodeJS Mentoring Swagger
 * NodeJS Mentoring Program API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ghari81189@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CityLocation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(
      require('../ApiClient'),
      require('./CityLocation')
    );
  } else {
    // Browser globals (root is window)
    if (!root.NodeJsMentoringSwagger) {
      root.NodeJsMentoringSwagger = {};
    }
    root.NodeJsMentoringSwagger.City = factory(
      root.NodeJsMentoringSwagger.ApiClient,
      root.NodeJsMentoringSwagger.CityLocation
    );
  }
})(this, function(ApiClient, CityLocation) {
  'use strict';

  /**
   * The City model module.
   * @module model/City
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>City</code>.
   * @alias module:model/City
   * @class
   * @param name {String}
   * @param country {String}
   */
  var exports = function(name, country) {
    var _this = this;

    _this['name'] = name;
    _this['country'] = country;
  };

  /**
   * Constructs a <code>City</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/City} obj Optional instance to populate.
   * @return {module:model/City} The populated <code>City</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = CityLocation.constructFromObject(data['location']);
      }
    }
    return obj;
  };

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {module:model/CityLocation} location
   */
  exports.prototype['location'] = undefined;

  return exports;
});
