/**
 * NodeJS Mentoring Swagger
 * NodeJS Mentoring Program API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ghari81189@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NodeJsMentoringSwagger) {
      root.NodeJsMentoringSwagger = {};
    }
    root.NodeJsMentoringSwagger.CityLocation = factory(
      root.NodeJsMentoringSwagger.ApiClient
    );
  }
})(this, function(ApiClient) {
  'use strict';

  /**
   * The CityLocation model module.
   * @module model/CityLocation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CityLocation</code>.
   * @alias module:model/CityLocation
   * @class
   * @param lat {Number}
   * @param _long {Number}
   */
  var exports = function(lat, _long) {
    var _this = this;

    _this['lat'] = lat;
    _this['long'] = _long;
  };

  /**
   * Constructs a <code>CityLocation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CityLocation} obj Optional instance to populate.
   * @return {module:model/CityLocation} The populated <code>CityLocation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('lat')) {
        obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
      }
      if (data.hasOwnProperty('long')) {
        obj['long'] = ApiClient.convertToType(data['long'], 'Number');
      }
    }
    return obj;
  };

  /**
   * @member {Number} lat
   */
  exports.prototype['lat'] = undefined;
  /**
   * @member {Number} long
   */
  exports.prototype['long'] = undefined;

  return exports;
});
